### ISSUE TITLE
Lesson4

### ISSUE THREAD

**Issue by artem130999** [Andrey-Pavlyuk/MyRepos#8]
Не выводит входящие данные перед подтверждением.

**Comment by Andrey-Pavlyuk** [comment]
Это наверное для Lesson3 issue ? Просто у меня Lesson3 - четвертая домашка , Lesson4 - пятая домашка. В третий там же просто теория была.

**Comment by artem130999** [comment]
> Это наверное для Lesson3 issue ? Просто у меня Lesson3 - четвертая домашка , Lesson4 - пятая домашка. В третий там же просто теория была.

Да, это для 4 домашки (3 Лесон)

**Comment by Andrey-Pavlyuk** [comment]
Я исправил issue.
